import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://prompt-maestro-electricidad.vercel.app';
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/niveles',
          '/niveles/*',
          '/simulaciones',
          '/simulaciones/*',
          '/calculadoras',
          '/calculadoras/*',
          '/recursos',
          '/recursos/*',
          '/foro',
          '/foro/*',
          '/blog',
          '/blog/*',
          '/eventos',
          '/eventos/*',
          '/leaderboard',
          '/ayuda',
          '/contacto',
        ],
        disallow: [
          '/api/*',
          '/auth/*',
          '/dashboard/*',
          '/admin/*',
          '/_next/*',
          '/private/*',
          '/temp/*',
          '/*.json$',
          '/*?*utm_*',
          '/*?*fbclid*',
          '/*?*gclid*',
          '/search?*',
          '/preview/*',
          '/draft/*',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/niveles',
          '/niveles/*',
          '/simulaciones',
          '/simulaciones/*',
          '/calculadoras',
          '/calculadoras/*',
          '/recursos',
          '/recursos/*',
          '/foro',
          '/foro/*',
          '/blog',
          '/blog/*',
          '/eventos',
          '/eventos/*',
          '/leaderboard',
          '/ayuda',
          '/contacto',
          '/sitemap.xml',
        ],
        disallow: [
          '/api/*',
          '/auth/*',
          '/dashboard/*',
          '/admin/*',
          '/_next/*',
          '/private/*',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/niveles',
          '/niveles/*',
          '/simulaciones',
          '/calculadoras',
          '/recursos',
          '/foro',
          '/blog',
          '/sitemap.xml',
        ],
        disallow: [
          '/api/*',
          '/auth/*',
          '/dashboard/*',
          '/admin/*',
        ],
        crawlDelay: 2,
      },
      {
        userAgent: 'facebookexternalhit',
        allow: [
          '/',
          '/niveles',
          '/niveles/*',
          '/blog',
          '/blog/*',
          '/eventos',
          '/eventos/*',
        ],
        disallow: [
          '/api/*',
          '/auth/*',
          '/dashboard/*',
          '/admin/*',
        ],
      },
      {
        userAgent: 'Twitterbot',
        allow: [
          '/',
          '/niveles',
          '/niveles/*',
          '/blog',
          '/blog/*',
          '/eventos',
          '/eventos/*',
        ],
        disallow: [
          '/api/*',
          '/auth/*',
          '/dashboard/*',
          '/admin/*',
        ],
      },
      {
        userAgent: 'LinkedInBot',
        allow: [
          '/',
          '/niveles',
          '/blog',
          '/blog/*',
          '/eventos',
          '/eventos/*',
        ],
        disallow: [
          '/api/*',
          '/auth/*',
          '/dashboard/*',
          '/admin/*',
        ],
      },
      {
        userAgent: [
          'AhrefsBot',
          'SemrushBot',
          'MJ12bot',
          'DotBot',
          'BLEXBot',
        ],
        disallow: '/',
        crawlDelay: 86400, // 24 horas
      },
      {
        userAgent: [
          'CCBot',
          'ChatGPT-User',
          'GPTBot',
          'Google-Extended',
          'anthropic-ai',
          'Claude-Web',
        ],
        disallow: '/',
      },
    ],
    sitemap: [
      `${baseUrl}/sitemap.xml`,
      `${baseUrl}/sitemap-levels.xml`,
      `${baseUrl}/sitemap-blog.xml`,
      `${baseUrl}/sitemap-resources.xml`,
    ],
    host: baseUrl,
  };
}

